sudo: required
dist: trusty
language: go
go:
- 1.7.x
env:
  global:
  - MONGODB_VERSION=3.2.11
  - ES_V5_URL=http://127.0.0.1:9205
  - ES_V2_URL=http://127.0.0.1:9202
  - ES_V1_URL=http://127.0.0.1:9201
  - EASYRSA_VARS_FILE=$HOME/gopath/src/github.com/compose/transporter/scripts/vars
before_install:
- openssl aes-256-cbc -K $encrypted_0967450889da_key -iv $encrypted_0967450889da_iv
  -in integration_tests/config.yml.enc -out integration_tests/config.yml -d
- openssl aes-256-cbc -K $encrypted_0967450889da_key -iv $encrypted_0967450889da_iv
  -in integration_tests/config.yml.enc -out integration_tests/config.yml -d
- if [[ $TRAVIS_EVENT_TYPE != 'cron' ]]; then ./scripts/before_install.sh; fi
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
script:
- "./scripts/tests.sh"
after_success:
- "$HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=/tmp/coverage.out"
services:
- docker
- postgresql
addons:
  postgresql: '9.4'
  apt:
    packages:
    - oracle-java8-set-default
before_script:
- if [[ $TRAVIS_EVENT_TYPE != 'cron' ]]; then ./scripts/before_script.sh; fi
after_script:
- mongo-orchestration stop
install: true
notifications:
  slack:
    secure: R8wvRnq0DcxiFNgUvJ3npnzY2LzU8uVyF8enqfxXNuSR3jRC2tqUosB5Qzb1CCiNicmpEwj3VTcwTozzCwcqckysFek3Pp2/oxYL8tRjqxks1zUeMHVv204l83Js8PAFVhODCQjIxZNQCdUM2fQ9q46MvdY7V8h/wGTbQKq1ZLE=
